collective/volto-form-block

- .gitignore
- src/components/Edit.jsx
- src/components/FormView.jsx
- src/components/Sidebar.jsx
They're optional and displayed in the form block only if filled in.
> Add title and description

- README.md
- package.json
- src/components/FormView.jsx
Adds [HCaptcha](https://www.hcaptcha.com) integration.
HCaptcha is ligher than ReCaptcha and respects users' privacy, so it is a good alternative I'd like to use: now it's possible here.
Updated README with docs on how to use captchas.
> HCaptcha integration

- README.md
- locales/de/LC_MESSAGES/volto.po
- locales/en/LC_MESSAGES/volto.po
- locales/es/LC_MESSAGES/volto.po
- locales/eu/LC_MESSAGES/volto.po
- locales/fr/LC_MESSAGES/volto.po
- locales/it/LC_MESSAGES/volto.po
- locales/ja/LC_MESSAGES/volto.po
- locales/nl/LC_MESSAGES/volto.po
- locales/pt/LC_MESSAGES/volto.po
- locales/pt_BR/LC_MESSAGES/volto.po
- locales/ro/LC_MESSAGES/volto.po
- locales/volto.pot
- src/components/EditBlock.jsx
- src/components/Field.css
- src/components/Field.jsx
- src/components/FormView.jsx
- src/components/Sidebar.jsx
Adds a static rich text field (not a fillable field, just text to display between other fields, editable in the edit view, the opposite of other fields)
> feat: add static rich text field

- locales/pt_BR/LC_MESSAGES/volto.po
> Update Brazilian Portuguese translation.

- locales/es/LC_MESSAGES/volto.po
- locales/eu/LC_MESSAGES/volto.po
> EU and ES Translations

- src/components/Sidebar.jsx
related to https://github.com/plone/volto/pull/2961
> fix: fixed ArrayWidget in sidebar

- src/components/View.jsx
- Fix the "send_to_backend" functionality. Now it doesn't send all the configured field parameters.
> Fix send_to_backend

- locales/de/LC_MESSAGES/volto.po
Fixes: #20
Add german translations to the Project.
> add german translations #20

- src/components/Sidebar.jsx
fixes https://github.com/collective/volto-form-block/issues/24
> flatten form data request URLs

- src/components/FormView.jsx
- src/components/View.jsx
> feat: do not reset the form when a backend error happens

- src/components/View.jsx
> fix: show only the error message and not the http error code

- package.json
- yarn.lock
This is breaking builds with 3.0.0 and latest Volto. Workaround is explicitly add the dep in your projects.
It would be great to have a release soon! Thanks!
> Add missing dep on volto-subblocks

- locales/de/LC_MESSAGES/volto.po
> Fix typo in de locale

- .gitignore
- locales/de/LC_MESSAGES/volto.po
- locales/en/LC_MESSAGES/volto.po
- locales/es/LC_MESSAGES/volto.po
- locales/eu/LC_MESSAGES/volto.po
- locales/fr/LC_MESSAGES/volto.po
- locales/it/LC_MESSAGES/volto.po
- locales/ja/LC_MESSAGES/volto.po
- locales/nl/LC_MESSAGES/volto.po
- locales/pt/LC_MESSAGES/volto.po
- locales/pt_BR/LC_MESSAGES/volto.po
- locales/ro/LC_MESSAGES/volto.po
- locales/volto.pot
- src/actions/index.js
- src/components/Sidebar.jsx
- src/components/Widget/SelectWidget.jsx
- src/formSchema.js
- src/helpers/react-select.js
related to https://github.com/collective/collective.volto.formsupport/pull/41
> data cleaning/wipe support

- src/components/Field.jsx
Fixes https://github.com/collective/volto-form-block/issues/90
> fix: Fix 'error is null' when adding form block.

- src/components/index.js
- src/index.js
saves 52kb
and 14kb Gzipped size
in main bundle
> chore: lazy loading components to improve bundle size

- src/components/FormResult.jsx
- src/components/FormView.jsx
- src/components/View.jsx
- src/components/index.js
- src/formSchema.js
- src/reducers/index.js
and not from current form compiled state
it requires https://github.com/collective/collective.volto.formsupport/pull/50
> fix: prevent xss in form block reading sent data from BE response

- locales/de/LC_MESSAGES/volto.po
add missing german translations
> feat: add missing german translations

- src/components/Edit.jsx
see https://github.com/collective/volto-form-block/issues/73
> fix: Fix bug that form data can not be loaded for forms in accordions

- README.md
- package.json
- src/components/Sidebar.jsx
- src/components/View.jsx
- src/components/Widget/CheckboxListWidget.jsx
- src/components/Widget/CheckboxWidget.jsx
- src/components/Widget/DatetimeWidget.jsx
- src/components/Widget/EmailWidget.jsx
- src/components/Widget/FileWidget.jsx
- src/components/Widget/RadioWidget.jsx
- src/components/Widget/SelectWidget.jsx
- src/components/Widget/TextWidget.jsx
- src/components/Widget/TextareaWidget.jsx
dates should be sent in ISO format (the widget's default should be fine), not DD-MM-YYYY
> fix: dates sent as ISO not DD-MM-YYYY

- locales/de/LC_MESSAGES/volto.po
- locales/en/LC_MESSAGES/volto.po
- locales/es/LC_MESSAGES/volto.po
- locales/eu/LC_MESSAGES/volto.po
- locales/fr/LC_MESSAGES/volto.po
- locales/it/LC_MESSAGES/volto.po
- locales/ja/LC_MESSAGES/volto.po
- locales/nl/LC_MESSAGES/volto.po
- locales/pt/LC_MESSAGES/volto.po
- locales/pt_BR/LC_MESSAGES/volto.po
- locales/ro/LC_MESSAGES/volto.po
- locales/volto.pot
- src/actions/index.js
- src/components/Field.jsx
- src/components/FormView.jsx
- src/components/Sidebar.jsx
- src/components/Widget/VisibilityConditionsWidget.css
- src/components/Widget/VisibilityConditionsWidget.jsx
- src/fieldSchema.js
- src/helpers/conditions-list.js
- src/index.js
- src/reducers/index.js
[Form edit]
[Modal to select conditions]
[Form view - hidden fields]
> feat: visible fields and conditions
